CoreProject/Controllers/ChartController.cs
using CoreProject.Data;
using CoreProject.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace CoreProject.Controllers
{
    [AllowAnonymous]
    public class ChartController : Controller
    {

        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ColumnIndex()
        {
            return View();
        }



        public IActionResult VisualizeItemResult()
        {
            return Json(ProductList());
        }
        public List<Class> ProductList()
        {
            List<Class> productListClass = new List<Class>();
            using (var c = new Context())
            {
                productListClass = c.Items.Select(x => new Class
                {
                    Stock = x.Stock,
                    ProductName=x.Name
                    
                }).ToList();
            }
            return productListClass;
        }



        public IActionResult Statistics()
        {
            Context c = new Context();

            var totalitem = c.Items.Count();
            ViewBag.totalitemVB = totalitem;

            var totalCategory = c.Categories.Count();
            ViewBag.totalCategoryVB = totalCategory;


            var lightingItemsType = c.Categories.Where(x => x.CategoryName == "Lighting").Select(y =>
            y.CategoryID).FirstOrDefault();
            ViewBag.lightingItemsVB = lightingItemsType;
            var lightingItems2 = c.Items.Where(x => x.CategoryID == lightingItemsType).Count();
            ViewBag.lightingItems2VB = lightingItems2;
            // Kaç çeşit Aydınlatma ürünü var

            var decorItemsType = c.Items.Where(x => x.CategoryID == c.Categories.Where(x => x.CategoryName == "Decor").Select(y =>
            y.CategoryID).FirstOrDefault()).Count();
            ViewBag.decorItemsVB = decorItemsType;
            // Kaç çeşit Dekor ürünü var

            var tableItemsType = c.Items.Where(x => x.CategoryID == c.Categories.Where(y => y.CategoryName == "Table").Select(z =>
            z.CategoryID).FirstOrDefault()).Count();
            ViewBag.tableItemsVB = tableItemsType;

            var mirrorItemsType = c.Items.Where(x => x.CategoryID == c.Categories.Where(y => y.CategoryName == "Mirror").Select(z =>
            z.CategoryID).FirstOrDefault()).Count();
            ViewBag.mirrorItemsVB = mirrorItemsType;

            var chairItemsType = c.Items.Where(x => x.CategoryID == c.Categories.Where(y => y.CategoryName == "Chair").Select(z =>
           z.CategoryID).FirstOrDefault()).Count();
            ViewBag.chairItemsVB = chairItemsType;


            var most = c.Items.OrderByDescending(x => x.Stock).Select(x => x.Name).FirstOrDefault();
            ViewBag.mostItemsVB = most;
            var quantity = c.Items.OrderByDescending(x => x.Stock).Select(x => x.Stock).FirstOrDefault();
            ViewBag.mostItemsQuantity = quantity;

            var mostExpensive = c.Items.OrderByDescending(x => x.Price).Select(x => x.Name).FirstOrDefault();
            ViewBag.mostExpensiveVB = mostExpensive;
            // fiyatına göre sırala ismini çek
            var expensive = c.Items.OrderByDescending(x => x.Price).Select(x => x.Price).FirstOrDefault();
            ViewBag.mostItemExpensiveVB = expensive;
            // fiyatına göre sırala fiyatını çek



            var allProductNumber = c.Items.Sum(x => x.Stock);
            ViewBag.allProductNumberVB = allProductNumber;

            var totalStockLightingID = c.Categories.Where(x => x.CategoryName == "Lighting").Select(y => y.CategoryID).FirstOrDefault();
            var totalStockLighting = c.Items.Where(y => y.CategoryID == totalStockLightingID).Sum(x => x.Stock);
            ViewBag.totalStockLightingID = totalStockLighting;

            var totalStockDecorID = c.Categories.Where(x => x.CategoryName == "Decor").Select(y => y.CategoryID).FirstOrDefault();
            var totalStockDecor = c.Items.Where(y => y.CategoryID == totalStockDecorID).Sum(x => x.Stock);
            ViewBag.totalStockDecorID = totalStockDecor;

            var totalStockTableID = c.Categories.Where(x => x.CategoryName == "Table").Select(y => y.CategoryID).FirstOrDefault();
            var totalStockTable = c.Items.Where(y => y.CategoryID == totalStockTableID).Sum(x => x.Stock);
            ViewBag.totalStockTableID = totalStockTable;

            var totalStockMirrorID = c.Categories.Where(x => x.CategoryName == "Mirror").Select(y => y.CategoryID).FirstOrDefault();
            var totalStockMirror = c.Items.Where(y => y.CategoryID == totalStockMirrorID).Sum(x => x.Stock);
            ViewBag.totalStockMirrorID = totalStockMirror;

            var totalStockChairID = c.Categories.Where(x => x.CategoryName == "Chair").Select(y => y.CategoryID).FirstOrDefault();
            var totalStockChair = c.Items.Where(y => y.CategoryID == totalStockChairID).Sum(x => x.Stock);
            ViewBag.totalStockChairID = totalStockChair;

            return View();
        }


    }
}

CoreProject/Views/Chart/ColumnIndex.cshtml
@{
    ViewData["Title"] = "ColumnIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Column View</h1>
<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeItemResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stock');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.productName, obj.stock]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Product - Stock",
                width: 800,
                height: 500,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('ColumnChart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="ColumnChart_div"></div>
   <br/>
    <div><a href="/Chart/Index" class="btn btn-info">Chart View</a></div>
</body>
</html>

CoreProject/Views/Chart/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Pie-Chart View</h1>



<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeItemResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stock');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.productName, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Product - Stock",
                width: 1000,
                height: 500,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>

    <div><a href="/Chart/ColumnIndex" class="btn btn-info">Column View</a></div>

</body>
</html>

CoreProject/Views/Chart/Statistics.cshtml
@{
    ViewData["Title"] = "Statistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Statistics</h1>

<!DOCTYPE html>
<html lang="tr">
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link href="~/web2/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>

    <div class="new-users" style="background-color:#2ecc71">

        <div class="icon-text">
            <h3>@ViewBag.totalitemVB </h3>
            <h4>Total Item</h4>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:goldenrod">
                <div class="icon-text">
                    <h3>@ViewBag.allProductNumberVB</h3>
                    <h4>The Total Number of All Products</h4>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:indianred">

                <div class="icon-text">
                    <h3>1</h3>
                    <p>Critic Stock</p>
                </div>
                <div class="clearfix"></div>
            </div>

            <div>
                 <div class="orders" style="background-color:khaki">

                <div class="icon-text">
                    <h3>The Most Quantity Product</h3>
                    <p>@ViewBag.mostItemsVB - <p>(Total @ViewBag.mostItemsQuantity Quantity)</p>
                
                   

                    
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="visitors" style="background-color:moccasin">

                <div class="icon-text">
                    <h3>The Highest Priced Product</h3>
                    <p>@ViewBag.mostExpensiveVB - <p>( @ViewBag.mostItemExpensiveVB ₺) per </p>
                 

                    
                </div>
                <div class="clearfix"></div>
            </div>
            </div>


            <div class="total">

                <div class="sales" style="background-color:cornflowerblue">
                    <div class="icon-text">
                        <h3>@ViewBag.totalCategoryVB</h3>
                        <p>Total Category</p>
                    </div>
                    <div class="sales" style="background-color:deepskyblue">

                        <div class="icon-text">
                            <h3>@ViewBag.lightingItems2VB</h3>
                            <p>Number of Lighting Product Types</p>
                           @* // Kaç ÇEŞİT Aydınlatma ürünü var (toplam stok sayısı değil, toplam ürün çeşidi sayısı.)*@
                        </div>
                        <div class="icon-text">
                            <h3>@ViewBag.totalStockLightingID</h3>
                            <p>Number of Total Lighting Product </p>
                           @* // Tüm Aydınlatma ürünlerinin toplam stok sayısı *@
                        </div>



                         <div class="icon-text">
                            <h3>@ViewBag.decorItemsVB</h3>
                            <p>Number of Decor Product Types</p>
                            @* // Kaç ÇEŞİT Dekor ürünü var ()*@
                        </div>
                         <div class="icon-text">
                            <h3>@ViewBag.totalStockDecorID</h3>
                            <p>Number of Total Decor Product </p>
                           @* // Tüm Dekor ürünlerinin toplam stok sayısı *@
                        </div>



                        <div class="icon-text">
                            <h3>@ViewBag.tableItemsVB</h3>
                            <p>Number of Table Product Types</p>
                            @* // Kaç ÇEŞİT Masa ürünü var ()*@
                        </div>
                         <div class="icon-text">
                            <h3>@ViewBag.totalStockTableID</h3>
                            <p>Number of Total Table Product </p>
                           @* // Tüm Masa ürünlerinin toplam stok sayısı *@
                        </div>




                        <div class="icon-text">
                            <h3>@ViewBag.mirrorItemsVB</h3>
                            <p>Number of Mirror Product Types</p>
                            @* // Kaç ÇEŞİT Ayna ürünü var ()*@
                        </div>
                         <div class="icon-text">
                            <h3>@ViewBag.totalStockMirrorID</h3>
                            <p>Number of Total Mirror Product </p>
                           @* // Tüm Ayna ürünlerinin toplam stok sayısı *@
                        </div>



                         <div class="icon-text">
                            <h3>@ViewBag.chairItemsVB</h3>
                            <p>Number of Chair Product Types</p>
                            @* // Kaç ÇEŞİT Sandalye ürünü var ()*@
                        </div>
                         <div class="icon-text">
                            <h3>@ViewBag.totalStockChairID</h3>
                            <p>Number of Total Chair Product </p>
                           @* // Tüm Sandalye ürünlerinin toplam stok sayısı *@
                        </div>

                    </div>
                </div>
            </div>
            @*
            @{ var total = ViewBag.totalCategoryVB; }
            @foreach (var item in collection)
            {

            }*@

        </div>
    </div>

</body>
</html>